name: Server Test

on:
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-server
  cancel-in-progress: true

jobs:
  ServerTest:
    uses: Mochi_753/GithubActions/.github/workflows/server-test.yml@1.20.1